services:
  frigate-viewer:
    #openssl s_client -key /etc/ssl/private/client.key -cert /etc/ssl/certs/client.crt  -CAfile /etc/ssl/certs/ca.pem -connect milvus.localdomain.localhost:19530
    image: ${DOCKERTARGETURL}frigate-viewer/frigate-viewer:$VERSION
    ports:
      - 8080:8080
      #image:  nexus.dev.god.de:5006/milvustestclient

    build:
      context:
        frigate-viewer
        #command:
        #bash -c 'sleep 900'
      platforms:
        - linux/amd64
        #- linux/arm64

    secrets:
      - source: ca-pem
        target: /etc/ssl/certs/ca.pem
      - source: client-crt
        target: /etc/ssl/certs/client.crt
      - source: client-key
        target: /etc/ssl/private/client.key
    #env_file:
    #  - secrets/frigate-viewer.ssl

  mosquitto:
    image: eclipse-mosquitto:openssl
    ports:
      - 1883:1883
      - 8883:8883
secrets:
  ca-pem:
    file: secrets/certs/ca.pem
  client-crt:
    file: secrets/certs/admin-cert.pem
  client-key:
    file: secrets/certs/admin-key.pem
  mqtt-key:
    file: secrets/certs/mqtt.example.com-key.pem
  mqtt-cert:
    file: secrets/certs/mqtt.example.com-cert.pem
