fullnameOverride: mosquitto

replicaCount: 1

image:
  repository: eclipse-mosquitto
  tag: 2.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8883

# cert-manager certificate configuration
certManager:
  enabled: true
  # Name of the cert-manager Issuer or ClusterIssuer to use
  issuerKind: ClusterIssuer
  issuerName: subca-issuer
  # The common name for the server certificate
  commonName: mosquitto.k3s1.lan
  # DNS names for the certificate
  dnsNames:
    - mosquitto.k3s1.lan

# Mosquitto configuration options
mosquitto:
  allowAnonymous: false
  useIdentityAsUsername: true
  persistence: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

traefikTCPIngress:
  enabled: true
  entryPoint: websecure
  hostSNI: "mosquitto.k3s1.lan"
