apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 8883
    protocol mqtt

    cafile /mosquitto/certs/ca.crt
    certfile /mosquitto/certs/tls.crt
    keyfile /mosquitto/certs/tls.key

    require_certificate true
    use_identity_as_username {{ .Values.mosquitto.useIdentityAsUsername | default "true" }}

    allow_anonymous {{ .Values.mosquitto.allowAnonymous | default "false" }}

    persistence {{ .Values.mosquitto.persistence | default "false" }}
