{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosquitto
  labels:
    app: mosquitto
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: mosquitto
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
{{- end }}

# NOTES:
# - For MQTT over TLS (port 8883), you typically want to use an ingress controller that supports TCP/TLS passthrough (e.g., NGINX with stream module, Traefik, or cloud load balancers).
# - Standard HTTP ingress controllers do not support raw MQTT/TLS traffic.
# - You may need to configure your ingress controller separately for TCP/TLS passthrough.
# - Example values.yaml:
#
# ingress:
#   enabled: true
#   host: mqtt.example.com
#   ingressClassName: nginx
#   annotations:
#     nginx.ingress.kubernetes.io/backend-protocol: "SSL"
#     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#   tls:
#     secretName: ""  # Leave empty for passthrough, or set if terminating TLS at ingress
